---
commit-depth: 0
debug: false
github-api-token: <token>>
github-targets:
  - mattyjones
  - sensu-plugins
gitlab-api-token: <token>>
gitlab-targets:
  - 5034914
  - mattyjones
ignore-extension:
  - .html
  - .css
  - .log
ignore-path:
  - static/
  - docs/
in-mem-clone: false
local-dirs:
  - ../wraith-test
match-level: 3
num-threads: 0
repo-dirs:
  - relative/path/to/repo
  - absolute/path/to/repo
signature-file: ../wraith-signatures/signatures/default.yml
silent: false
